# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - pihole_net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - ${PIHOLE_WEB_PORT}:80/tcp  # Optional: Expose Pi-hole's web interface HTTP on a different host port
      - ${PIHOLE_HTTPS_PORT}:443/tcp  # Optional: Expose HTTPS (self-signed certificate) on a different host port
      # Uncomment below if using Pi-hole as your DHCP server
      # - "67:67/udp"
    environment:
      TZ: 'America/Toronto'
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      # Uncomment if using DNSMASQ persistence from v5 migration
      # FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - ${PIHOLE_DATA_VOLUME}/etc-pihole:/etc/pihole
      # Uncomment if migrating dnsmasq configs
      # - ${PIHOLE_DATA_VOLUME}/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN   # Needed for DHCP
      - SYS_TIME    # Needed for NTP time sync
      - SYS_NICE    # Optional: gives Pi-hole higher process priority
    restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
